### mysql
druid:
  driverClass: com.mysql.jdbc.Driver
  initialSize: 5
  maxActive: 50
  maxIdle: 15
  maxWait: 60000
  minIdle: 10
  password: NelFr4CKBow9jcw6kD2XXg
  testOnBorrow: true
  url: jdbc:mysql://172.16.4.7:3306/Urine
  username: doctorwork_dev
# \u540E\u7AEF\u5730\u5740
project:
  h5: http://web-dev.doctorwork.com
  path: http://mojing-qa.developer.doctorwork.com/qie-doctor
  ssr: http://ssr-dev.doctorwork.com
### swagger
swagger:
  enable: true
access:
  pre:
    path: http://mojing.developer.doctorwork.com/qie-doctor/wechat/auth/access?scope=1

#\u4F01\u9E45\u533B\u751F\u516C\u4F17\u53F7 \u6B63\u5F0F\u7684
ris:
  wechat:
    mp:
      aesKey: NKzkrNp80XQZxf0J7xJ1ususiV7NeEfg8aAg4JyZhdY
      appId: wx236c9418c338d8a5
      appId.appName: est-wx-ris
      secret: e5e4d40130dbffa1cd336149de74a3e2
      token: cduhope2007

spring:
  data:
    mongodb:
      uri: mongodb://dev:Doctorwork_dev@172.16.4.7:27017/MagicMirror
  dubbo:
    application:
      name: ris-wx
      owner: yxw

    registry:
      address: zookeeper://172.16.5.6:2181
    protocol:
      port: 90102
  redis:
    sentinel:
      master: mymaster
      nodes: 172.16.4.7:6380
    database: 15
    password: Doctorwork6379
sso:
  address: http://sso-dev.doctorwork.com

oa:
  sso:
    addr: http://oa.sso.developer.doctorwork.com/console